/** Stable codes returned in API error envelopes. */
export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
  REPOSITORY_ERROR: 'REPOSITORY_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  CONNECTION_ERROR: 'CONNECTION_ERROR',
  AGENT_MODEL_NOT_FOUND: 'AGENT_MODEL_NOT_FOUND',
  AGENT_AUTH_UNAVAILABLE: 'AGENT_AUTH_UNAVAILABLE',
  AGENT_PROVIDER_UNAVAILABLE: 'AGENT_PROVIDER_UNAVAILABLE',
  AGENT_SESSION_START_FAILED: 'AGENT_SESSION_START_FAILED',
  AGENT_CONFIG_INVALID: 'AGENT_CONFIG_INVALID',
} as const;
