// Repository-owned dependency policy. Runtime invocations must use LOCKED_COMMANDS.
export const PINNED_PYTHON_VERSION = '3.14.6';
export const SCRIPT_DEPENDENCY_SET = [
  { name: 'pandas', version: '3.0.6' },
  { name: 'openpyxl', version: '3.1.5' },
  { name: 'xlsxwriter', version: '3.2.9' },
  { name: 'plotly', version: '7.1.0' },
  { name: 'matplotlib', version: '3.11.2' },
  { name: 'jinja2', version: '3.1.6' },
  { name: 'python-dateutil', version: '2.9.0.post0' },
  { name: 'pytest', version: '9.1.1' },
] as const;
export const VERIFICATION_TOOL_SET = [
  { name: 'ruff', version: '0.16.9' },
  { name: 'bandit', version: '1.9.4' },
] as const;
export type CheckerTool = (typeof VERIFICATION_TOOL_SET)[number]['name'];
export const FORBIDDEN_UV_ARGS = ['add', 'remove', 'pip', 'lock'] as const;
/** Spawn uv directly, including its executable suffix on Windows. */
export const uvCommand = (platform: NodeJS.Platform): string => platform === 'win32' ? 'uv.exe' : 'uv';

/**
 * Render an exact, non-package uv project from the dependency policy.
 * @param set The repository-approved package and version pairs.
 * @param pythonVersion Exact CPython patch version.
 * @returns Reproducible TOML to commit and copy into the data root.
 * @example renderPyproject(SCRIPT_DEPENDENCY_SET, PINNED_PYTHON_VERSION)
 */
export function renderPyproject(set: readonly { readonly name: string; readonly version: string }[], pythonVersion = PINNED_PYTHON_VERSION): string {
  return [
    '# Generated by pnpm runtime:lock. Update the dependency policy, then regenerate.',
    '[project]',
    'name = "automate-runtime"',
    'version = "0.0.0"',
    `requires-python = "==${pythonVersion}"`,
    `dependencies = [${set.map(({ name, version }) => JSON.stringify(`${name}==${version}`)).join(', ')}]`,
    '',
    '[tool.uv]',
    'package = false',
    '',
  ].join('\n');
}

/** Exact argument vectors allowed to reach uv in production. */
export const LOCKED_COMMANDS = {
  probe: (): readonly string[] => ['--version'],
  findPython: (version: string): readonly string[] => ['python', 'find', version],
  installPython: (version: string): readonly string[] => ['python', 'install', version],
  prepare: (project: string): readonly string[] => ['sync', '--locked', '--project', project],
  runScript: (project: string, launcher: string, entrypoint: string): readonly string[] => ['run', '--project', project, '--no-sync', '--locked', '--', 'python', launcher, entrypoint],
  runTests: (project: string): readonly string[] => ['run', '--project', project, '--no-sync', '--locked', '--', 'python', '-m', 'pytest', '-q'],
  runChecker: (project: string, tool: CheckerTool, args: readonly string[]): readonly string[] => ['run', '--project', project, '--no-sync', '--locked', '--', tool, ...args],
  inspect: (project: string, script: string): readonly string[] => ['run', '--project', project, '--no-sync', '--locked', '--', 'python', '-c', script],
} as const;

/**
 * Describe the importable script packages from the one policy source.
 * @returns Comma-separated package names with exact versions.
 * @example describeDependencySet()
 */
export function describeDependencySet(): string {
  return SCRIPT_DEPENDENCY_SET.map(({ name, version }) => `${name} ${version}`).join(', ');
}
