import { Type, type Static } from '@sinclair/typebox';
import { AsOfSchema } from '../reuse/as-of';
import { CompatibilityReportSchema } from '../reuse/compatibility';
import { InputContractSchema } from '../reuse/input-contract';
import { RepairMappingSchema } from '../reuse/mapping';
import { TEMPLATE_NAME_MAX_CHARS, TEMPLATE_PAGE_MAX } from '../reuse/limits';
import { CodeFileSchema, DeclaredOutputSchema } from './generation-api';
import { TaskSchema, ExecutionSummarySchema } from './task-api';

const Closed = { additionalProperties: false } as const;
const Id = Type.Integer({ minimum: 1 });
const Digest = Type.String({ pattern: '^[0-9a-f]{64}$' });
const Nullable = <T extends ReturnType<typeof Type.String>>(schema: T) => Type.Union([schema, Type.Null()]);
export const TemplateIdParamsSchema = Type.Object({ id: Id }, Closed);
export const TemplateListQuerySchema = Type.Object({ cursor: Type.Optional(Id), limit: Type.Optional(Type.Integer({ minimum: 1, maximum: TEMPLATE_PAGE_MAX })) }, Closed);
export const TemplateCompatibilityQuerySchema = Type.Object({ uploadIds: Type.Array(Id, { minItems: 1, uniqueItems: true }), asOfDate: Type.Optional(Type.String()), timeZone: Type.Optional(Type.String()) }, Closed);
export const SaveExecutionRequestSchema = Type.Object({ name: Type.Optional(Type.String({ maxLength: TEMPLATE_NAME_MAX_CHARS })), templateId: Type.Optional(Id) }, Closed);
export const StartTemplateRunRequestSchema = Type.Object({ uploadIds: Type.Array(Id, { minItems: 1, uniqueItems: true }), compatibilityDigest: Digest, asOf: Type.Optional(AsOfSchema), asOfDate: Type.Optional(Type.String()), timeZone: Type.Optional(Type.String()) }, Closed);
export const TemplateConsentSchema = Type.Object({ consentId: Id, payloadDigest: Digest }, Closed);
export const StartTemplateRepairRequestSchema = Type.Object({ uploadIds: Type.Array(Id, { minItems: 1, uniqueItems: true }), mapping: RepairMappingSchema, consent: TemplateConsentSchema, asOfDate: Type.Optional(Type.String()), timeZone: Type.Optional(Type.String()) }, Closed);
export const RepairExecutionRequestSchema = Type.Object({ mapping: Type.Optional(RepairMappingSchema), consent: TemplateConsentSchema, note: Type.Optional(Type.String()) }, Closed);
export const TemplateSummarySchema = Type.Object({ id: Id, name: Type.String(), currentRevisionNumber: Id, revisionCount: Type.Integer({ minimum: 1 }), runCount: Type.Integer({ minimum: 0 }), lastRunAt: Nullable(Type.String()), createdAt: Type.String() }, Closed);
export const TemplateSchema = Type.Object({ id: Id, name: Type.String(), description: Type.String(), createdAt: Type.String(), updatedAt: Type.String() }, Closed);
export const TemplateRevisionSummarySchema = Type.Object({ id: Id, number: Id, createdAt: Type.String(), sourceExecutionId: Type.Union([Id, Type.Null()]), note: Nullable(Type.String()) }, Closed);
export const TemplateRevisionSchema = Type.Object({ id: Id, number: Id, createdAt: Type.String(), contentDigestShort: Type.String(), summary: Type.String(), declaredOutputs: Type.Array(DeclaredOutputSchema), inputs: InputContractSchema.properties.inputs, rules: InputContractSchema.properties.rules, notes: InputContractSchema.properties.notes, runtimeLine: Type.String(), readsWallClock: Type.Array(Type.Object({ path: Type.String(), line: Id }, Closed)), note: Nullable(Type.String()) }, Closed);
export const TemplateListResponseSchema = Type.Object({ items: Type.Array(TemplateSummarySchema), nextCursor: Type.Union([Id, Type.Null()]), hasMore: Type.Boolean() }, Closed);
export const TemplateDetailResponseSchema = Type.Object({ template: TemplateSchema, currentRevision: TemplateRevisionSchema, revisions: Type.Array(TemplateRevisionSummarySchema) }, Closed);
export const TemplateRevisionDetailResponseSchema = Type.Object({ revision: TemplateRevisionSchema, files: Type.Array(CodeFileSchema) }, Closed);
export const SavePreviewResponseSchema = Type.Object({ saveable: Type.Boolean(), reason: Nullable(Type.String()), alreadySaved: Type.Union([Type.Object({ templateId: Id, name: Type.String(), revisionNumber: Id }, Closed), Type.Null()]), defaultName: Type.String(), promoteTarget: Type.Union([Type.Object({ templateId: Id, name: Type.String(), nextRevisionNumber: Id }, Closed), Type.Null()]), keeps: Type.Object({ inputs: Type.Array(Type.Object({ label: Type.String(), format: Type.String(), sheets: Type.Array(Type.String()), requiredColumns: Type.Array(Type.String()) }, Closed)), ruleCount: Type.Integer(), noteCount: Type.Integer() }, Closed), readsWallClock: Type.Array(Type.Object({ path: Type.String(), line: Id }, Closed)) }, Closed);
export const SaveExecutionResponseSchema = Type.Object({ template: TemplateSchema, revision: TemplateRevisionSummarySchema }, Closed);
export const CompatibilityResponseSchema = Type.Object({ report: CompatibilityReportSchema, digest: Digest, asOf: AsOfSchema }, Closed);
export const StartTemplateRunResponseSchema = Type.Object({ task: TaskSchema, execution: ExecutionSummarySchema }, Closed);
export const ReplayResponseSchema = Type.Object({ execution: ExecutionSummarySchema }, Closed);
export const DeleteTemplateResponseSchema = Type.Object({ templateId: Id, removed: Type.Object({ revisions: Type.Integer({ minimum: 0 }) }, Closed), runsKept: Type.Integer({ minimum: 0 }) }, Closed);

export type TemplateCompatibilityQuery = Static<typeof TemplateCompatibilityQuerySchema>;
export type SaveExecutionRequest = Static<typeof SaveExecutionRequestSchema>;
export type StartTemplateRunRequest = Static<typeof StartTemplateRunRequestSchema>;
export type StartTemplateRepairRequest = Static<typeof StartTemplateRepairRequestSchema>;
export type RepairExecutionRequest = Static<typeof RepairExecutionRequestSchema>;
export type TemplateListResponse = Static<typeof TemplateListResponseSchema>;
export type TemplateDetailResponse = Static<typeof TemplateDetailResponseSchema>;
export type TemplateRevisionDetailResponse = Static<typeof TemplateRevisionDetailResponseSchema>;
export type SavePreviewResponse = Static<typeof SavePreviewResponseSchema>;
export type CompatibilityResponse = Static<typeof CompatibilityResponseSchema>;
export type SaveExecutionResponse = Static<typeof SaveExecutionResponseSchema>;
export type StartTemplateRunResponse = Static<typeof StartTemplateRunResponseSchema>;
export type ReplayResponse = Static<typeof ReplayResponseSchema>;
export type DeleteTemplateResponse = Static<typeof DeleteTemplateResponseSchema>;
